In [8]:
import pandas as pd

from script import pre_process

In [ ]:
# TODO BIG OLE BUG!!!!!!!!!!!!!!!!!! line 45 scripts.py
# NPS doesn't let you get the last item when calling .str.split

MVRR_df = MVRR_df = pd.read_csv("MVRR_data_Oct19_forclass.csv")

x, y = pre_process(MVRR_df, "MVRR")
x

Started with 840 rows...
Ending with 826, dropping 14 rows.

      subjectID verb_of_interest_itemized verb_of_interest  adjusted_response
0    1791687692                arrested_2         arrested          88.666667
1    1791687692               captured_12         captured          34.666667
2    1791687692               consumed_14         consumed          11.666667
3    1791687692              described_11        described          53.000000
4    1791687692              displayed_10        displayed          64.333333
..          ...                       ...              ...                ...
275  1792377438                    sold_8             sold           0.000000
276  1792377438              supported_13        supported          66.666667
277  1792377438                 treated_1          treated          33.333333
278  1792377438                    used_7             used         100.000000
279  1792377438               welcomed_19         welcomed           0.000000

[280 rows x 4 columns]

In [10]:
y

   verb_of_interest_itemized verb_of_interest  adjusted_response
0                welcomed_19         welcomed          15.714286
1               monitored_20        monitored          16.857143
2               described_11        described          31.904762
3                consumed_14         consumed          35.309524
4                captured_12         captured          35.833333
5                     used_7             used          47.166667
6                    hired_4            hired          47.476190
7                reviewed_18         reviewed          48.321429
8                  treated_1          treated          51.571429
9                escorted_16         escorted          52.416667
10              supported_13        supported          53.285714
11               reviewed_17         reviewed          55.166667
12             recognized_15       recognized          58.476190
13                 offered_6          offered          60.666667
14                    sold_8             sold          66.404762
15                 rescued_5          rescued          67.380952
16              displayed_10        displayed          69.023810
17                     led_3              led          69.642857
18                punished_9         punished          73.261905
19                arrested_2         arrested          74.785714

In [11]:
NPS_df = pd.read_csv("NPS_data_Oct19_forclass.csv")

x, y = pre_process(NPS_df, "NPS")
x

Started with 1260 rows...
Ending with 1232, dropping 28 rows.

      subjectID verb_of_interest_itemized verb_of_interest  adjusted_response
0    1791791154                  bonus_13            bonus          18.666667
1    1791791154               character_6        character          33.000000
2    1791791154                  crisis_8           crisis           0.000000
3    1791791154                   data_16             data          14.000000
4    1791791154                    data_9             data           8.666667
..          ...                       ...              ...                ...
415  1792376327                  rumor_19            rumor          55.666667
416  1792376327                  score_18            score          48.666667
417  1792376327              statement_12        statement          69.000000
418  1792376327                teenager_7         teenager          41.666667
419  1792376327                 winner_15           winner          42.000000

[420 rows x 4 columns]

In [12]:
y

   verb_of_interest_itemized verb_of_interest  adjusted_response
0               operation_20        operation          25.682540
1                   crisis_8           crisis          29.833333
2                     data_9             data          32.920635
3                  driver_14           driver          33.206349
4                   score_18            score          33.777778
5                   issue_11            issue          34.158730
6                  opinion_4          opinion          36.309524
7                  winner_15           winner          36.698413
8                     plan_5             plan          36.841270
9                 decision_3         decision          37.071429
10               character_6        character          37.801587
11                  rumor_19            rumor          41.134921
12                 problem_1          problem          42.841270
13                   lady_17             lady          42.984127
14                  money_10            money          43.150794
15                   data_16             data          45.515873
16              statement_12        statement          46.126984
17                  bonus_13            bonus          48.301587
18             interviewer_2      interviewer          50.761905
19                teenager_7         teenager          57.738095