In [1]:
import pandas as pd

from script import pre_process

In [2]:
# TODO BIG OLE BUG!!!!!!!!!!!!!!!!!! line 45 scripts.py
# NPS doesn't let you get the last item when calling .str.split

MVRR_df = MVRR_df = pd.read_csv("MVRR_data_Oct19_forclass.csv")

x, y = pre_process(MVRR_df, "MVRR")
x

Started with 840 rows...
Ending with 826, dropping 14 rows.

      subjectID matrix_verb_itemized matrix_verb  adjusted_response
0    1791687692            arrested2    arrested          88.666667
1    1791687692           captured12    captured          34.666667
2    1791687692           consumed14    consumed          11.666667
3    1791687692          described11   described          53.000000
4    1791687692          displayed10   displayed          64.333333
..          ...                  ...         ...                ...
275  1792377438                sold8        sold           0.000000
276  1792377438          supported13   supported          66.666667
277  1792377438             treated1     treated          33.333333
278  1792377438                used7        used         100.000000
279  1792377438           welcomed19    welcomed           0.000000

[280 rows x 4 columns]

In [3]:
y

   matrix_verb_itemized matrix_verb  adjusted_response
0            welcomed19    welcomed          15.714286
1           monitored20   monitored          16.857143
2           described11   described          31.904762
3            consumed14    consumed          35.309524
4            captured12    captured          35.833333
5                 used7        used          47.166667
6                hired4       hired          47.476190
7            reviewed18    reviewed          48.321429
8              treated1     treated          51.571429
9            escorted16    escorted          52.416667
10          supported13   supported          53.285714
11           reviewed17    reviewed          55.166667
12         recognized15  recognized          58.476190
13             offered6     offered          60.666667
14                sold8        sold          66.404762
15             rescued5     rescued          67.380952
16          displayed10   displayed          69.023810
17                 led3         led          69.642857
18            punished9    punished          73.261905
19            arrested2    arrested          74.785714

In [ ]:
NPS_df = pd.read_csv("NPS_data_Oct19_forclass.csv")

x, y = pre_process(NPS_df, "NPS")

Started with 1260 rows...
Ending with 1232, dropping 28 rows.

In [18]:
import spacy

nlp = spacy.load("en_core_web_sm")

def extract_main_verb(sentence):
    doc = nlp(sentence)
    return next(
        (token.text for token in doc
         if token.dep_ == "ROOT" and token.pos_ == "VERB"),
        None
    )

df["main_verb"] = df["sentence_fragment"].map(
    {s: extract_main_verb(s)
     for s in df["sentence_fragment"].dropna().unique()}
)

In [19]:
df['main_verb'].sort_values().unique()

<StringArray>
[  'arrested',   'captured',   'consumed',  'described',  'displayed',
   'escorted',      'hired',        'led',  'monitored',    'offered',
   'punished', 'recognized',    'rescued',   'reviewed',       'sold',
  'supported',    'treated',       'used',   'welcomed']
Length: 19, dtype: str

In [20]:
df[["item", "sentence_fragment", "main_verb"]].drop_duplicates().sort_values("item")

   item                   sentence_fragment   main_verb
6     1          The injured runner treated     treated
9    10      The ancient artifact displayed   displayed
5    11     The captivating photo described   described
18   12          The corrupt ruler captured    captured
1    13       The talented artist supported   supported
20   14           The tiny insects consumed    consumed
11   15  The Oscar-winning actor recognized  recognized
8    16         The famous athlete escorted    escorted
13   17           The recent paper reviewed    reviewed
42   18         The exciting study reviewed    reviewed
27   19          The charming host welcomed    welcomed
0     2    The passionate activist arrested    arrested
38   20       The attentive nurse monitored   monitored
39    3               The student group led         led
17    4          The hardworking chef hired       hired
12    5           The missing hiker rescued     rescued
30    6              The remote job offered     offered
7     7                The new machine used        used
4     8                 The poor slave sold        sold
2     9    The rebellious prisoner punished    punished